### ISSUE TITLE
Building ITW texture model issue

### ISSUE THREAD

**Issue by thrillerist** [menpo/itwmm#2]
Hi, 
there's error when building the ITW texture model. 
`itw_texture_model, X, m = generate_texture_model_from_image_3d_fits(features_and_fits_32bit[:n_imgs_for_rpca])`

Traceback (most recent call last):
...
  File "C:\Users\thril\Documents\GitHub\itwmm\itwmm\model\__init__.py", line 63, in generate_texture_model_from_image_3d_fits
    features, mask = extract_per_vertex_colour_with_occlusion(fit_2d, img)

  File "C:\Users\thril\Documents\GitHub\itwmm\itwmm\model\extractimage.py", line 130, in extract_per_vertex_colour_with_occlusion
    render_diag=render_diag)

  File "C:\Users\thril\Documents\GitHub\itwmm\itwmm\model\extractimage.py", line 26, in per_vertex_occlusion
    bc, ti = rasterize_barycentric_coordinate_images(mesh, shape)

  File "C:\Anaconda3\lib\site-packages\menpo3d\rasterize\cpu.py", line 151, in rasterize_barycentric_coordinate_images
    tri_indices_img = np.zeros((1, h, w), dtype=int)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by jiajunzhang16** [comment]
Also meet the same error, have you solved the problem? 
Many thanks.

**Comment by KhanhDinhDuy** [comment]
I also meet this error :(((

**Comment by KhanhDinhDuy** [comment]
In this file: /anaconda3/envs/menpo/lib/python3.5/site-packages/menpo3d/rasterize/cpu.py
we need to add this line after the "h, w = image_shape":
h, w = int(h), int(w)
This will resolve my issue because h,w can be float numbers
